# Generated by Django 4.1.7 on 2023-02-15 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("churn", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Kaki",
        ),
    ]
