# Generated by Django 4.1.7 on 2023-03-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churn', '0002_delete_kaki'),
    ]

    operations = [
        migrations.AddField(
            model_name='back',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
