# Generated by Django 4.1.7 on 2023-03-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("churn", "0003_back_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data",
            name="gender",
        ),
        migrations.AddField(
            model_name="data",
            name="contract",
            field=models.CharField(
                choices=[
                    ("Month-to-month", "Month-to-month"),
                    ("One year", "One year"),
                    ("Two year", "Two year"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
